[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "event-horizon-shell"
version = "1.1.2"
authors = [
    { name = "QUIK1001", email = "your-email@example.com" }
]
description = "Event Horizon Shell - terminal interface"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools]
packages = ["EHS"]

[project.urls]
Homepage = "https://github.com/QUIK1001/Event-Horizon-Shell"
