name: TEST PyPi Publish

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Debug
      run: |
        echo "Workflow is running!"
        echo "Secret exists: ${{ secrets.PYPI_API_TOKEN != '' }}"
